[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./img" },
]

# ignore file not found when running scripts
ignored_error_codes = [1878]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
